# SMITH Framework Configuration
# All paths should be absolute.

# Root directory of the SMITH Framework itself.
# Contains tools, logs, memory, etc.
smith_root_dir: /data/data/com.termux/files/home/SMITH_FRAMEWORK

# Default root directory for the projects the agent works on.
# This can be overridden on a per-project basis.
default_project_root: /data/data/com.termux/files/home/QIKI_DTMP
